### ISSUE TITLE
DefaultArrayBuf is too large for an esp32 stack

### ISSUE THREAD

**Issue by thinkrapido** [felixwrt/sml-rs#32]
https://github.com/felixwrt/sml-rs/blame/b2b98edf0a92fe0d137e8f4302bf9776f4ac698d/src/lib.rs#L482

Place the buffer on the heap

**Comment by thinkrapido** [comment]
2 * 1024 is appropriate, but I think this won't store all the data.

**Comment by felixwrt** [comment]
There's two options here:
- if you're using the heap, you'll have access to alloc::vec::Vec. Simply use that and the buffer will be on the heap. Note: you'll have to activate the alloc feature of the crate.
- you can probably change the stack size. I'm pretty sure I did that when I was working with esp-idf. If its possible there, it should also be possible in non-idf projects.

**Comment by felixwrt** [comment]
Hi Romeo, I'm closing this issue as I haven't heard back from you. Feel free to reopen if you still have issues with the lib.
