### ISSUE TITLE
SML Attention

### ISSUE THREAD

**Issue by Arne91** [felixwrt/sml-rs#34]
Hello there,

The project is very interesting for us. But I am missing parts like parsing the sml attention responses. It would be useful to have it as a separate parse event or part of the message start (as part of the streaming parser).

Are there any plans to implement this in the future?

I am interested in your opinion.

Best regards,
Arne

**Comment by felixwrt** [comment]
As far as I know, this crate has up to now only been used to passively listen to the data stream sent by smart meters, so there's never been a use case for attention responses. I'm open to implement support though. Could you share your use case? That would make it easier for me to understand what's needed and how it should be implemented. It would also make for good tests. 

Best regards,
Felix

**Comment by Arne91** [comment]
One use case might be to log a communication between two devices as a passive listener. One device sends commands and the other device sends responses. In this case, the requested smart meter could throw an attention message, which may be interesting for debugging or logging purposes.

Best regards,
Arne

**Comment by felixwrt** [comment]
Could you provide test data for such a scenario? I'd like to have some real world data to test the implementation. 

I don't have much time for this project currently so I can't make any promises. If you'd be interested in doing the implementation though, I'd try to offer assistance and reviews.

**Comment by felixwrt** [comment]
Hi @Arne91, I'm closing this as I haven't heard back from you. Feel free to reopen if you're still interested in the topic.
